name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies for GetSnippetTask project
      run: dotnet restore GetSnippetTask/GetSnippetTask.csproj

    - name: Install dependencies for SnippetsUnitTests project
      run: dotnet restore unittests/SnippetsUnitTests.csproj
      
    - name: Build
      run: dotnet build GetSnippetTask/GetSnippetTask.csproj  --configuration Release --no-restore

    - name: Test
      run: dotnet test unittests/SnippetsUnitTests.csproj --no-restore --verbosity normal
