name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build GetSnippetTask/GetSnippetTask.csproj  --configuration Release --no-restore

    - name: Test
      run: dotnet test unittests/SnippetsUnitTests.csproj --no-restore --verbosity normal
