name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies for GetSnippetTask project
      run: dotnet restore GetSnippetTask/GetSnippetTask.csproj

    - name: Install dependencies for SnippetsUnitTests project
      run: dotnet restore unittests/SnippetsUnitTests.csproj
      
    - name: Build
      run: dotnet build GetSnippetTask/GetSnippetTask.csproj  --configuration Release --no-restore

    - name: Test
      run: dotnet test unittests/SnippetsUnitTests.csproj --no-restore --verbosity normal

    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
       PROJECT_FILE_PATH: GetSnippetTask/GetSnippetTask.csproj
       NUGET_KEY: ${{secrets.NUGET_APIKEY}}
